kernel:
  # Sobel Gx
  - [-1, 0, 1]
  - [-2, 0, 2]
  - [-1, 0, 1]

# kernel:
#   # Sobel Gy
#   - [-1, -2, -1]
#   - [0,   0,  0]
#   - [1,   2,  1]

# kernel:
#   # Identity
#   - [0, 0, 0]
#   - [0, 1, 0]
#   - [0, 0, 0]

# kernel:
#   # 3x3 Gaussian
#   - [0.0625, 0.125, 0.0625]
#   - [0.125,  0.25,  0.125]
#   - [0.0625, 0.125, 0.0625]
